### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String nl.hnogames.domoticz.Containers.ExtendedStatusInfo.getName()' on a null object reference

### ISSUE THREAD

**Issue by galadril** [galadril/DomoticzForAndroid#151]
``` bash
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String nl.hnogames.domoticz.Containers.ExtendedStatusInfo.getName()' on a null object reference
    at nl.hnogames.domoticz.Fragments.Switches.onSwitchClick(Switches.java:407)
    at nl.hnogames.domoticz.Adapters.SwitchesAdapter.handleOnOffSwitchClick(SwitchesAdapter.java:696)
    at nl.hnogames.domoticz.Adapters.SwitchesAdapter.access$100(SwitchesAdapter.java:52)
    at nl.hnogames.domoticz.Adapters.SwitchesAdapter$11.onCheckedChanged(SwitchesAdapter.java:576)
    at android.widget.CompoundButton.setChecked(CompoundButton.java:154)
    at android.widget.Switch.setChecked(Switch.java:862)
    at android.widget.Switch.toggle(Switch.java:857)
    at android.widget.CompoundButton.performClick(CompoundButton.java:118)
    at android.view.View$PerformClick.run(View.java:19881)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5292)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)

```

**Comment by galadril** [comment]
Fixed in next version
