### ISSUE TITLE
android.content.res.Resources$NotFoundException: String resource ID #0x290

### ISSUE THREAD

**Issue by galadril** [galadril/DomoticzForAndroid#155]
``` bash
android.content.res.Resources$NotFoundException: String resource ID #0x290
    at android.content.res.Resources.getText(Resources.java:312)
    at android.widget.TextView.setText(TextView.java:4422)
    at nl.hnogames.domoticz.UI.WeatherInfoDialog.show(WeatherInfoDialog.java:85)
    at nl.hnogames.domoticz.Fragments.Weather.showInfoDialog(Weather.java:127)
    at nl.hnogames.domoticz.Fragments.Weather.access$500(Weather.java:29)
    at nl.hnogames.domoticz.Fragments.Weather$1$1.onItemLongClick(Weather.java:98)
    at android.widget.AbsListView.showContextMenuForChild(AbsListView.java:3194)
    at android.view.View.showContextMenu(View.java:5298)
    at android.view.View.performLongClick(View.java:5246)
    at android.view.View$CheckForLongPress.run(View.java:21127)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5417)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

```

**Comment by galadril** [comment]
I don't really get how this crash could happen... 
It's like a string resource id was not available on runtime??

**Comment by galadril** [comment]
I think it has something to do with the french translation not being complete (or contains wrong strings..)

http://stackoverflow.com/questions/29843131/android-content-res-resourcesnotfoundexception-string-array-resource-id-0x7f0

**Comment by galadril** [comment]
Maybe we should remove the current French translation and do it again via Crowndin..

**Comment by RoadXY** [comment]
I agree.

**Comment by galadril** [comment]
@fchauveau sorry we're going to remove the french translations for now...
They are causing crashes...

We're going to use a translation service, RoadXY wil guide you!

**Comment by fchauveau** [comment]
Okay I'll look further on how this bug could append.

**Comment by RoadXY** [comment]
We have Crowdin almost ready now:
https://crowdin.com/project/domoticz-for-android
