### ISSUE TITLE
java.lang.IllegalStateException: Fragment Dashboard{41a47908} not attached to Activity

### ISSUE THREAD

**Issue by galadril** [galadril/DomoticzForAndroid#180]
``` bash
java.lang.IllegalStateException: Fragment Dashboard{41a47908} not attached to Activity
    at android.support.v4.app.Fragment.getResources(Fragment.java:639)
    at android.support.v4.app.Fragment.getString(Fragment.java:661)
    at nl.hnogames.domoticz.app.DomoticzFragment.errorHandling(DomoticzFragment.java:167)
    at nl.hnogames.domoticz.Fragments.Dashboard.errorHandling(Dashboard.java:570)
    at nl.hnogames.domoticz.Fragments.Dashboard$1.onError(Dashboard.java:136)
    at nl.hnogames.domoticz.Domoticz.DevicesParser.onError(DevicesParser.java:91)
    at nl.hnogames.domoticz.Utils.RequestUtil$7.onResponse(RequestUtil.java:153)
    at nl.hnogames.domoticz.Utils.RequestUtil$7.onResponse(RequestUtil.java:140)
    at com.android.volley.toolbox.JsonRequest.deliverResponse(JsonRequest.java:65)
    at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)
    at android.os.Handler.handleCallback(Handler.java:725)
    at android.os.Handler.dispatchMessage(Handler.java:92)
    at android.os.Looper.loop(Looper.java:176)
    at android.app.ActivityThread.main(ActivityThread.java:5319)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:511)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
    at dalvik.system.NativeStart.main(Native Method)

```

**Comment by RoadXY** [comment]
Fragment Dashboard{41a47908} not attached to Activity

Wtf, how is that even possible?

**Comment by galadril** [comment]
It's possible, when a async thread gets the switches (for example), then comes back in the receiver. but the app is already closed...

This is probably an exception that the user probably never sees, I think it happens under water

**Comment by galadril** [comment]
fixed by RoadXY  in next version
