### ISSUE TITLE
App Crashes when removing GeoFence Location

### ISSUE THREAD

**Issue by galadril** [galadril/DomoticzForAndroid#41]
App Crashes when removing GeoFence Location!

java.util.ConcurrentModificationException
    at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
    at nl.hnogames.domoticz.Utils.SharedPrefUtil.removeLocation(SharedPrefUtil.java:482)
    at nl.hnogames.domoticz.GeoSettingsActivity$4$1.onClick(GeoSettingsActivity.java:183)
    at android.support.v7.app.AlertController$ButtonHandler.handleMessage(AlertController.java:157)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:136)
    at android.app.ActivityThread.main(ActivityThread.java:5146)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)

**Comment by galadril** [comment]
Fixed in v0.1.138

**Comment by RoadXY** [comment]
Was about to post this issue but needed to create a bug/crash report, lol

**Comment by galadril** [comment]
I saw the exception coming by on Splunk Mint :)

**Comment by RoadXY** [comment]
Damn your fast! :+1:
