### ISSUE TITLE
Geofence - phone without Google Play Services crashes

### ISSUE THREAD

**Issue by RoadXY** [galadril/DomoticzForAndroid#5]
```
11-18 22:31:47.616 19133-19133/nl.hnogames.domoticz W/GooglePlayServicesUtil: Google Play services is missing.
11-18 22:31:47.616 19133-19133/nl.hnogames.domoticz W/GooglePlayServicesUtil: Google Play services is missing.
11-18 22:31:47.616 19133-19133/nl.hnogames.domoticz W/GooglePlayServicesUtil: Google Play services is missing.
11-18 22:31:47.616 19133-19133/nl.hnogames.domoticz W/GooglePlayServicesUtil: Google Play services is missing.
11-18 22:31:47.616 19133-19133/nl.hnogames.domoticz W/GooglePlayServicesUtil: Google Play services is missing.
11-18 22:31:47.616 19133-19133/nl.hnogames.domoticz W/GooglePlayServicesUtil: Google Play services is missing.
11-18 22:31:47.616 19133-19133/nl.hnogames.domoticz W/GooglePlayServicesUtil: Google Play services is missing.
11-18 22:31:47.616 19133-19133/nl.hnogames.domoticz W/GooglePlayServicesUtil: Google Play services is missing.
11-18 22:31:47.616 19133-19133/nl.hnogames.domoticz W/GooglePlayServicesUtil: Google Play services is missing.
11-18 22:31:47.625 19133-19133/nl.hnogames.domoticz W/GooglePlayServicesUtil: Google Play services is missing.
11-18 22:31:47.625 19133-19133/nl.hnogames.domoticz E/GeoSettings: Google Play services is unavailable.
11-18 22:31:47.645 19133-19133/nl.hnogames.domoticz D/AndroidRuntime: Shutting down VM
11-18 22:31:47.645 19133-19133/nl.hnogames.domoticz W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0xb2cbf908)
11-18 22:31:47.675 19133-19138/nl.hnogames.domoticz D/dalvikvm: GC_CONCURRENT freed 408K, 8% free 8506K/9192K, paused 10ms+1ms, total 19ms
11-18 22:31:48.526 19133-19138/nl.hnogames.domoticz D/dalvikvm: GC_CONCURRENT freed 2126K, 21% free 8302K/10488K, paused 4ms+0ms, total 9ms
11-18 22:31:50.715 19133-19133/nl.hnogames.domoticz E/AndroidRuntime: FATAL EXCEPTION: main
11-18 22:31:50.715 19133-19133/nl.hnogames.domoticz E/AndroidRuntime: java.lang.NullPointerException
11-18 22:31:50.715 19133-19133/nl.hnogames.domoticz E/AndroidRuntime:     at nl.hnogames.domoticz.GeoSettingsActivity.onCreateOptionsMenu(GeoSettingsActivity.java:269)
11-18 22:31:50.715 19133-19133/nl.hnogames.domoticz E/AndroidRuntime:     at android.app.Activity.onCreatePanelMenu(Activity.java:2490)
11-18 22:31:50.715 19133-19133/nl.hnogames.domoticz E/AndroidRuntime:     at android.support.v4.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:298)
11-18 22:31:50.715 19133-19133/nl.hnogames.domoticz E/AndroidRuntime:     at android.support.v7.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:85)
11-18 22:31:50.715 19133-19133/nl.hnogames.domoticz E/AndroidRuntime:     at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.onCreatePanelMenu(AppCompatDelegateImplBase.java:241)
11-18 22:31:50.715 19133-19133/nl.hnogames.domoticz E/AndroidRuntime:     at android.support.v7.app.AppCompatDelegateImplV7.preparePanel(AppCompatDelegateImplV7.java:1273)
11-18 22:31:50.715 19133-19133/nl.hnogames.domoticz E/AndroidRuntime:     at android.support.v7.app.AppCompatDelegateImplV7.doInvalidatePanelMenu(AppCompatDelegateImplV7.java:1553)
11-18 22:31:50.715 19133-19133/nl.hnogames.domoticz E/AndroidRuntime:     at android.support.v7.app.AppCompatDelegateImplV7.access$100(AppCompatDelegateImplV7.java:89)
11-18 22:31:50.715 19133-19133/nl.hnogames.domoticz E/AndroidRuntime:     at android.support.v7.app.AppCompatDelegateImplV7$1.run(AppCompatDelegateImplV7.java:129)
11-18 22:31:50.715 19133-19133/nl.hnogames.domoticz E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:725)
11-18 22:31:50.715 19133-19133/nl.hnogames.domoticz E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:92)
11-18 22:31:50.715 19133-19133/nl.hnogames.domoticz E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:137)
11-18 22:31:50.715 19133-19133/nl.hnogames.domoticz E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5041)
11-18 22:31:50.715 19133-19133/nl.hnogames.domoticz E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method)
11-18 22:31:50.715 19133-19133/nl.hnogames.domoticz E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:511)
11-18 22:31:50.715 19133-19133/nl.hnogames.domoticz E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
11-18 22:31:50.715 19133-19133/nl.hnogames.domoticz E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
11-18 22:31:50.715 19133-19133/nl.hnogames.domoticz E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method)
```

![geofence - phone without google play services crashes](https://cloud.githubusercontent.com/assets/3482284/11256550/c96eaf92-8e4c-11e5-83e6-559f1a10db62.png)

**Comment by galadril** [comment]
Weird.. because i do check if it's available:
    if (!isGooglePlayServicesAvailable()) {
            Toast.makeText(this, "Google Play services unavailable.", Toast.LENGTH_SHORT).show();
            finish();
            return;
        }

**Comment by RoadXY** [comment]
I'll look into the code to see if anything comes up.

**Comment by galadril** [comment]
Does this still happen in 0.1.133 ?

**Comment by RoadXY** [comment]
No, perfect!
